# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi_framework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuxijobruntime',
            name='server_ip',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
