# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi_framework', '0002_fuxijobruntime_server_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuxiactionruntime',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuxiactionruntime',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fuxiactionruntime',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fuxijobruntime',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fuxijobruntime',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fuxijobruntime',
            name='schedule_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fuxitaskruntime',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fuxitaskruntime',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fuxitaskruntime',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
