# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 15:06
"""
auto generated
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    auto generated
    """

    dependencies = [
        ('fuxi_framework', '0003_auto_20170505_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuxiPermissionInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'fuxi_permission_info',
            },
        ),
        migrations.CreateModel(
            name='FuxiRoleInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=64)),
                ('permission', models.ForeignKey(null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    to='fuxi_framework.FuxiPermissionInfo', to_field='permission')),
            ],
            options={
                'db_table': 'fuxi_role_info',
            },
        ),
        migrations.CreateModel(
            name='FuxiUserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32)),
                ('user_type', models.IntegerField()),
                ('role', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=64)),
                ('module', models.CharField(max_length=64)),
                ('fuxi_app', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'fuxi_user_info',
            },
        ),
        migrations.AlterField(
            model_name='fuxiactionruntime',
            name='action_content',
            field=models.TextField(),
        ),
    ]
