# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("params", jsonfield.fields.JSONField(default={})),
                ("extra_data", jsonfield.fields.JSONField(default={})),
                ("errors", jsonfield.fields.JSONField(default={})),
                ("action_content", models.TextField()),
                ("seq_id", models.IntegerField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField(null=True)),
                ("finish_time", models.DateTimeField(null=True)),
                ("timeout", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=64)),
                ("result", models.TextField(default="")),
                ("error", models.TextField(default="")),
            ],
            options={
                "db_table": "gearbull_action",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ActionTree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("root",
                 picklefield.fields.PickledObjectField(editable=False)),
                ("trees",
                 picklefield.fields.PickledObjectField(editable=False)),
                ("state", models.CharField(default="NEW", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="FlowMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("params", jsonfield.fields.JSONField(default={})),
                ("extra_data", jsonfield.fields.JSONField(default={})),
                ("errors", jsonfield.fields.JSONField(default={})),
                ("task_type", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("params", jsonfield.fields.JSONField(default={})),
                ("extra_data", jsonfield.fields.JSONField(default={})),
                ("errors", jsonfield.fields.JSONField(default={})),
                ("priority", models.CharField(max_length=10)),
                ("threshold", models.CharField(max_length=5)),
                ("progress", models.CharField(max_length=5)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("schedule_time", models.DateTimeField(null=True)),
                ("finish_time", models.DateTimeField(null=True)),
                ("pause_time", models.DateTimeField(null=True)),
                ("latest_heartbeat", models.CharField(max_length=32)),
                ("timeout", models.CharField(max_length=10)),
                ("control_action", models.CharField(max_length=32)),
                ("user", models.CharField(max_length=32)),
                ("server_ip", models.CharField(max_length=32)),
                ("state", models.CharField(max_length=64)),
                ("is_manual", models.BooleanField(default=False)),
                ("task_type", models.CharField(default="", max_length=128)),
                ("tasks_plan", jsonfield.fields.JSONField(default={})),
                ("fail_rate", models.IntegerField(default=0)),
                ("fail_count", models.IntegerField(default=0)),
                ("concurrency", models.IntegerField(default=1)),
                ("continue_after_stage_finish",
                 models.BooleanField(default=False)),
            ],
            options={
                "db_table": "gearbull_job",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(max_length=255, unique=True)),
                ("cur_number", models.IntegerField(default=0)),
                ("max_number", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("params", jsonfield.fields.JSONField(default={})),
                ("extra_data", jsonfield.fields.JSONField(default={})),
                ("errors", jsonfield.fields.JSONField(default={})),
                ("priority", models.CharField(max_length=10)),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_name", models.CharField(max_length=64)),
                ("threshold", models.CharField(max_length=5)),
                ("progress", models.CharField(max_length=5)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField(null=True)),
                ("finish_time", models.DateTimeField(null=True)),
                ("timeout", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=64)),
                ("task_type", models.CharField(default="", max_length=128)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WorkFlow.Job"),
                ),
            ],
            options={
                "db_table": "gearbull_task",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dynamic_thresholds", jsonfield.fields.JSONField(default={})),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="actiontree",
            name="task",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="WorkFlow.Task",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="WorkFlow.Task"),
        ),
    ]
