# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-02 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("WorkFlow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("etype", models.CharField(max_length=128)),
                ("operate_logs", jsonfield.fields.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name="Runtime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", jsonfield.fields.JSONField(default={})),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("stats", jsonfield.fields.JSONField(default={})),
                ("stat_time", models.CharField(max_length=128)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="is_executed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="confirms",
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="job",
            name="is_idempotency",
            field=models.BooleanField(default=False),
        ),
    ]
