# Generated by Django 2.2.6 on 2019-11-02 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("WorkFlow", "0002_auto_20191102_1158"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
