# Generated by Django 2.2.6 on 2019-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkFlow", "0004_auto_20191102_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="method_name",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="action",
            name="tree_name",
            field=models.CharField(default="", max_length=128),
        ),
    ]
