# Generated by Django 2.2.6 on 2019-12-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkFlow", "0005_auto_20191211_1810"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="state_update_time",
            field=models.DateTimeField(null=True),
        ),
    ]
