# Generated by Django 2.2.6 on 2019-12-14 14:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("WorkFlow", "0006_job_state_update_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="stage_states",
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
