# Generated by Django 2.2.6 on 2019-12-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WorkFlow", "0008_auto_20191215_0920"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="stage_states",
        ),
    ]
