# Generated by Django 2.2.6 on 2019-12-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkFlow", "0009_remove_job_stage_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="executor",
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name="job",
            name="juuid",
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name="job",
            name="server_ip",
            field=models.CharField(max_length=128),
        ),
    ]
