# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuxi_framework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_params', jsonfield.fields.JSONField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fuxi_framework.FuxiJobRuntime', to_field='job_id')),
            ],
        ),
    ]
