# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 13:54
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjing', '0002_taskplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskPlan',
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='tasks_plan',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
