# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 14:03
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjing', '0003_auto_20170416_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='job_params',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='tasks_plan',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
