# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi_framework', '0002_fuxijobruntime_server_ip'),
        ('zhongjing', '0006_auto_20170416_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster', models.CharField(max_length=64)),
                ('app', models.CharField(max_length=64)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fuxi_framework.FuxiTaskRuntime', to_field='task_id')),
            ],
        ),
    ]
