# -*- coding: utf-8 -*-
""" 
0008_taskinfo_reason.py
"""
# Generated by Django 1.10.6 on 2017-04-27 11:26
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """ Migration """

    dependencies = [
        ('zhongjing', '0007_taskinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='reason',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
