# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-05-17 14:11
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """
    Migration
    """

    dependencies = [
        ('zhongjing', '0009_taskinfo_task_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='app',
            field=models.CharField(max_length=1024),
        ),
    ]
