# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-06-05 19:56
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """ Migration """

    dependencies = [
        ('zhongjing', '0010_auto_20170517_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sli',
            fields=[
                ('id', models.AutoField(auto_created=True,
                    primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=64)),
                ('calc_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
