# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-06-05 21:03
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """ migrations """

    dependencies = [
        ('zhongjing', '0011_sli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sli',
            name='value',
            field=models.FloatField(),
        ),
    ]
