# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-06-06 15:52
"""
from __future__ import unicode_literals

from django.db import migrations 
from django.db import models


class Migration(migrations.Migration):
    """Migration """

    dependencies = [
        ('zhongjing', '0013_auto_20170606_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='sli',
            name='target',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
