# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-06-08 15:43
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """ Migration """

    dependencies = [
        ('zhongjing', '0014_sli_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='sli',
            name='uuid',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
