# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-06-13 11:00
"""
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):
    """ Migration """

    dependencies = [
        ('zhongjing', '0015_sli_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sli',
            name='extra_data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
