# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-06-19 16:31
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """ Migration """

    dependencies = [
        ('zhongjing', '0016_sli_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sli',
            name='service',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
