# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongjing', '0017_sli_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
