# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-07-04 14:44
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models
import jsonfield.fields


class Migration(migrations.Migration):
    """ migrations """

    dependencies = [
        ('zhongjing', '0018_jobinfo_is_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, 
                    serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('json_data', jsonfield.fields.JSONField(default={})),
            ],
        ),
    ]
