# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-07-04 16:53
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models
import django.utils.timezone


class Migration(migrations.Migration):
    """ Migration """

    dependencies = [
        ('zhongjing', '0019_jsondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='save_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
