# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-07-07 14:22
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """ Migration """

    dependencies = [
        ('zhongjing', '0020_jsondata_save_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, 
                    serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('save_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
