# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-08-11 10:52
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """ Migration """

    dependencies = [
        ('zhongjing', '0022_jobinfo_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='task_type',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
