# -*- coding: utf-8 -*-
"""
# Generated by Django 1.10.6 on 2017-10-31 20:20
"""
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Migration"""

    dependencies = [
        ('zhongjing', '0023_taskinfo_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faillog',
            name='job_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
